version: '3.1'

# A useful compose file for local development.
# This compose file contains preconfigured services for many common development needs
# and can be used to quickly start up a development environment for Metabase.
#
# usage: docker-compose -f dev/docker-compose.yml --profile e2e up -d
#
# Available profiles:
# - e2e: data dbs, notifications, sso and snowplow required to run e2e tests locally
# - app-dbs: Postgres and MySQL databases for Metabase to connect to
# - data-dbs: Sample databases for testing Metabase
# - notifications: Maildev and webhook-tester for testing email and webhook notifications
# - sso: SAML and LDAP for testing SSO
# - snowplow: Snowplow micro for testing Snowplow
#


services:
  app-db-postgres:
    image: postgres:latest
    container_name: metabase-postgres-app-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metabase
    profiles:
      - app-dbs
    networks:
      - metabasenet

  app-db-mysql:
    image: mysql:latest
    container_name: metabase-mysql57-app-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mbuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: metabase
    profiles:
      - app-dbs
    networks:
      - metabasenet

  data-postgres-14:
    image: metabase/qa-databases:postgres-sample-14
    container_name: metabasedb_postgres_14_data
    ports:
      - "15432:5432"
    restart: always
    profiles:
      - data-dbs
      - e2e
    networks:
      - metabasenet

  data-mysql-5.7:
    image: metabase/qa-databases:mysql-sample-5.7
    container_name: metabasedb_mysql_5_7_data
    environment:
      - TZ=US/Pacific
    ports:
      - 23306:3306
    restart: always
    profiles:
      - data-dbs
    networks:
      - metabasenet

  data-mysql-8:
    image: metabase/qa-databases:mysql-sample-8
    container_name: metabasedb_mysql_8_data
    ports:
      - 5404:5432
    restart: always
    profiles:
      - data-dbs
      - e2e
    networks:
      - metabasenet

  data-mongo-6:
    image: metabase/qa-databases:mongo-sample-6
    container_name: metabasedb_mongo_6_data
    restart: always
    ports:
      - 27004:27017
    profiles:
      - data-dbs
      - e2e
    networks:
      - metabasenet

  data-vertica-12:
    image: vertica/vertica-ce:12.0.2-0
    container_name: metabasedb_vertica_data
    restart: always
    ports:
      - "5433:5433"
    profiles:
      - data-dbs
    networks:
      - metabasenet

  maildev:
    image: maildev/maildev:latest
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    profiles:
      - notifications
      - e2e
    networks:
      - metabasenet

  webhook-tester:
    image: tarampampam/webhook-tester:latest
    container_name: webhook-tester
    command: |
      serve --create-session 00000000-0000-0000-0000-000000000000 && \
        while ! nc -z localhost 9080; do sleep 1; done && \
        echo -e "Webhook tester is up and running!"
    ports:
      - "9080:8080"
    profiles:
      - notifications
      - e2e
    networks:
      - metabasenet

  saml:
    build: https://github.com/mcguinness/saml-idp.git
    volumes:
      - ./idp-private-key.pem:/idp-private-key.pem
      - ./idp-public-cert.pem:/idp-public-cert.pem
    ports:
      - "7000:7000"
    entrypoint:
      - node
      - app.js
      - --host
      - "0.0.0.0"
      - --port
      - "7000"
      - --acs
      - https://foo.okta.com/auth/saml20/example
      - --aud
      - https://www.okta.com/saml2/service-provider/spf5aFRRXFGIMAYXQPNV"
    profiles:
      - sso
    networks:
      - metabasenet

  ldap:
    image: bitnami/openldap:2.6.4
    container_name: ldap
    ports:
      - "389:389"
    environment:
      LDAP_ADMIN_PASSWORD: adminpass
      LDAP_USERS: user01@example.org,user02@example.org
      LDAP_PASSWORDS: 123456,123465
      LDAP_ROOT: dc=example,dc=org
      LDAP_PORT_NUMBER: 389
    profiles:
      - sso
      - e2e
    networks:
      - metabasenet

  snowplow-micro:
    image: snowplow/snowplow-micro:1.2.1
    ports:
      - "9090:9090"
    volumes:
      - .:/config
    command: "--collector-config /config/micro.conf --iglu /config/iglu.json"
    profiles:
      - snowplow
      - e2e
    networks:
      - metabasenet

networks:
  metabasenet:
