name: Test database driver
inputs:
  junit-name:
    required: true
    default: 'driver'
  test-args:
    required: false

runs:
  using: "composite"
  steps:
    - name: Prepare front-end environment
      uses: ./.github/actions/prepare-frontend
    - name: Prepare back-end environment
      uses: ./.github/actions/prepare-backend
      with:
        m2-cache-key: driver-${{ inputs.junit-name }}
    - name: Build static viz frontend
      run: yarn build-static-viz
      shell: bash
    - name: Test database driver
      run: clojure -X:dev:ci:ee:ee-dev:drivers:drivers-dev:test ${{ inputs.test-args }}
      shell: bash

