name: E2E Tests using Replay.io browser

on: [push, pull_request]

jobs:
  e2e-matrix-builder:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.e2e-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate matrix for E2E tests
        id: e2e-matrix
        uses: ./.github/actions/build-e2e-matrix

  e2e-tests:
    needs: e2e-matrix-builder
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 90
    name: e2e-tests-${{ matrix.name }}-${{ matrix.edition }}
    env:
      MB_EDITION: ${{ matrix.edition }}
      DISPLAY: ""
      QA_DB_ENABLED: true
      # Any env starting with `CYPRESS_` will be available to all Cypress tests via `Cypress.env()`
      # Example: you can get `CYPRESS_FOO` with `Cypress.env("FOO")`
      CYPRESS_ALL_FEATURES_TOKEN: ${{ secrets.ENTERPRISE_TOKEN }}
      CYPRESS_NO_FEATURES_TOKEN: ${{ secrets.E2E_STARTER_TOKEN }}
      MB_SNOWPLOW_AVAILABLE: true
      MB_SNOWPLOW_URL: "http://localhost:9090" # Snowplow micro
      TZ: US/Pacific # to make node match the instance tz
      TERM: xterm
      CYPRESS_REPLAYIO_ENABLED: 1
      RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata.json
      RECORD_REPLAY_METADATA_TEST_RUN_ID: ${{ github.run_id }}
      REPLAY_API_KEY: ${{ secrets.REPLAY_IO_TOKEN }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.e2e-matrix-builder.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Important in case we need to download uberjar from previous commits!
          fetch-depth: 20

      - name: Prepare Docker containers
        uses: ./.github/actions/e2e-prepare-containers
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          maildev: true
          openldap: ${{ startsWith(matrix.name, 'admin') }}
          postgres: ${{ matrix.name != 'mongo'}}
          mysql: ${{ matrix.name != 'mongo'}}
          mongo: ${{ matrix.name == 'mongo'}}

      - name: Download Metabase ${{ matrix.edition }} uberjar
        uses: ./.github/actions/e2e-download-uberjar
        with:
          edition: ${{ matrix.edition }}

      - name: Prepare front-end environment
        uses: ./.github/actions/prepare-frontend
      - name: Prepare JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"

      - name: Prepare Cypress environment
        id: cypress-prep
        uses: ./.github/actions/prepare-cypress
        with:
          is-replay-browser: true

      - name: Run Snowplow micro
        uses: ./.github/actions/run-snowplow-micro

      - name: Run e2e/test/scenarios/admin/settings/settings.cy.spec.js
        run: |
          yarn run test-cypress-run \
          --spec 'e2e/test/scenarios/admin/settings/settings.cy.spec.js' \
          --browser "replay-chromium"

      - name: Upload replays
        if: always()
        uses: replayio/action-upload@v0.5.1
        with:
          api-key: ${{ secrets.REPLAY_API_KEY }}
